name: code-quality

on: [push, pull_request]

jobs:
  flake8-pydocstyle:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install and run flake8
        run: |
          pip install --upgrade pip
          pip install flake8
          flake8 nnights/
          
      - name: install and run pydocstyle
        run:
          pip install pydocstyle
          pydocstyle nnights/ 